
package vs.online.voterservice.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-12T15:29:49.549+05:30
 * Generated source version: 3.1.10
 * 
 */
public final class OnlineVoterService_VoterServiceSOAP_Client {

    private static final QName SERVICE_NAME = new QName("http://www.online.vs/VoterService/", "VoterService");

    private OnlineVoterService_VoterServiceSOAP_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = VoterService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        VoterService ss = new VoterService(wsdlURL, SERVICE_NAME);
        OnlineVoterService port = ss.getVoterServiceSOAP();  
        
        {
        System.out.println("Invoking getVoteDetailsByVoterId...");
        java.lang.String _getVoteDetailsByVoterId_input = "_getVoteDetailsByVoterId_input1537911910";
        vs.online.voterservice.types.User _getVoteDetailsByVoterId__return = port.getVoteDetailsByVoterId(_getVoteDetailsByVoterId_input);
        System.out.println("getVoteDetailsByVoterId.result=" + _getVoteDetailsByVoterId__return);


        }
        {
        System.out.println("Invoking getVoteActivity...");
        java.lang.String _getVoteActivity_input = "_getVoteActivity_input-330911632";
        vs.online.voterservice.types.ActivityResponse _getVoteActivity__return = port.getVoteActivity(_getVoteActivity_input);
        System.out.println("getVoteActivity.result=" + _getVoteActivity__return);


        }
        {
        System.out.println("Invoking addVote...");
        vs.online.voterservice.types.VoterInfo _addVote_input = new vs.online.voterservice.types.VoterInfo();
        _addVote_input.setVoterId(-340468585);
        _addVote_input.setName("Name-182431203");
        _addVote_input.setState("State-254333553");
        _addVote_input.setDist("Dist-1477065732");
        _addVote_input.setGender("Gender-804655480");
        _addVote_input.setAge(24610093);
        _addVote_input.setVoterType("VoterType-1968714697");
        _addVote_input.setCandidatesSign("CandidatesSign968636371");
        try {
            vs.online.voterservice.types.VoterResponse _addVote__return = port.addVote(_addVote_input);
            System.out.println("addVote.result=" + _addVote__return);

        } catch (ServiceActivityException e) { 
            System.out.println("Expected exception: ServiceActivityException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
