package vs.online.voterservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-12T15:29:50.136+05:30
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "VoterService", 
                  wsdlLocation = "http://localhost:8080/EasyVoteStatus/services/vote/VoterService?wsdl",
                  targetNamespace = "http://www.online.vs/VoterService/") 
public class VoterService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.online.vs/VoterService/", "VoterService");
    public final static QName VoterServiceSOAP = new QName("http://www.online.vs/VoterService/", "VoterServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/EasyVoteStatus/services/vote/VoterService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VoterService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/EasyVoteStatus/services/vote/VoterService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VoterService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VoterService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VoterService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public VoterService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VoterService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VoterService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OnlineVoterService
     */
    @WebEndpoint(name = "VoterServiceSOAP")
    public OnlineVoterService getVoterServiceSOAP() {
        return super.getPort(VoterServiceSOAP, OnlineVoterService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OnlineVoterService
     */
    @WebEndpoint(name = "VoterServiceSOAP")
    public OnlineVoterService getVoterServiceSOAP(WebServiceFeature... features) {
        return super.getPort(VoterServiceSOAP, OnlineVoterService.class, features);
    }

}
