
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package vs.online.voterservice.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-03-12T15:29:50.012+05:30
 * Generated source version: 3.1.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "VoterService",
                      portName = "VoterServiceSOAP",
                      targetNamespace = "http://www.online.vs/VoterService/",
                      wsdlLocation = "http://localhost:8080/EasyVoteStatus/services/vote/VoterService?wsdl",
                      endpointInterface = "vs.online.voterservice.client.OnlineVoterService")
                      
public class VoterServiceSOAPImpl implements OnlineVoterService {

    private static final Logger LOG = Logger.getLogger(VoterServiceSOAPImpl.class.getName());

    /* (non-Javadoc)
     * @see vs.online.voterservice.client.OnlineVoterService#getVoteDetailsByVoterId(java.lang.String input)*
     */
    public vs.online.voterservice.types.User getVoteDetailsByVoterId(java.lang.String input) { 
        LOG.info("Executing operation getVoteDetailsByVoterId");
        System.out.println(input);
        try {
            vs.online.voterservice.types.User _return = new vs.online.voterservice.types.User();
            vs.online.voterservice.types.VoterInfo _returnVoterInfo = new vs.online.voterservice.types.VoterInfo();
            _returnVoterInfo.setVoterId(208938483);
            _returnVoterInfo.setName("Name789078780");
            _returnVoterInfo.setState("State1701010828");
            _returnVoterInfo.setDist("Dist167521107");
            _returnVoterInfo.setGender("Gender1662924559");
            _returnVoterInfo.setAge(1981215900);
            _returnVoterInfo.setVoterType("VoterType-448952886");
            _returnVoterInfo.setCandidatesSign("CandidatesSign2104459591");
            _return.setVoterInfo(_returnVoterInfo);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see vs.online.voterservice.client.OnlineVoterService#getVoteActivity(java.lang.String input)*
     */
    public vs.online.voterservice.types.ActivityResponse getVoteActivity(java.lang.String input) { 
        LOG.info("Executing operation getVoteActivity");
        System.out.println(input);
        try {
            vs.online.voterservice.types.ActivityResponse _return = new vs.online.voterservice.types.ActivityResponse();
            _return.setVoteCount(1233282625);
            java.util.List<vs.online.voterservice.types.VoterInfo> _returnVoterInfo = new java.util.ArrayList<vs.online.voterservice.types.VoterInfo>();
            vs.online.voterservice.types.VoterInfo _returnVoterInfoVal1 = new vs.online.voterservice.types.VoterInfo();
            _returnVoterInfoVal1.setVoterId(1841339036);
            _returnVoterInfoVal1.setName("Name-628772605");
            _returnVoterInfoVal1.setState("State2102911829");
            _returnVoterInfoVal1.setDist("Dist-823773062");
            _returnVoterInfoVal1.setGender("Gender-481296485");
            _returnVoterInfoVal1.setAge(1422283810);
            _returnVoterInfoVal1.setVoterType("VoterType-672724805");
            _returnVoterInfoVal1.setCandidatesSign("CandidatesSign-1640610340");
            _returnVoterInfo.add(_returnVoterInfoVal1);
            _return.getVoterInfo().addAll(_returnVoterInfo);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see vs.online.voterservice.client.OnlineVoterService#addVote(vs.online.voterservice.types.VoterInfo input)*
     */
    public vs.online.voterservice.types.VoterResponse addVote(vs.online.voterservice.types.VoterInfo input) throws ServiceActivityException   { 
        LOG.info("Executing operation addVote");
        System.out.println(input);
        try {
            vs.online.voterservice.types.VoterResponse _return = new vs.online.voterservice.types.VoterResponse();
            _return.setVoterId(-1958404067);
            _return.setResponse("Response1235794477");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ServiceActivityException("ServiceActivityException...");
    }

}
